apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-deploy
spec:
  selector:
    matchLabels:
      app: proj
  replicas: 3
  template:
    metadata:
      labels:
        app: proj
    spec:
      containers:
      - name: proj_container
        image: amrakmal/proj_img:latest
        ports:
        - containerPort: 80